apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sheameyers-com-tls
spec:
  secretName: sheameyers-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sheameyers.com
  dnsNames:
    - sheameyers.com
    - www.sheameyers.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sheameyers.com
          - www.sheameyers.com
